#!/bin/bash -f
./voz1b1 eight_halos.raw 0.1 1 8H 2 0 0 0
./voz1b1 eight_halos.raw 0.1 1 8H 2 0 0 1
./voz1b1 eight_halos.raw 0.1 1 8H 2 0 1 0
./voz1b1 eight_halos.raw 0.1 1 8H 2 0 1 1
./voz1b1 eight_halos.raw 0.1 1 8H 2 1 0 0
./voz1b1 eight_halos.raw 0.1 1 8H 2 1 0 1
./voz1b1 eight_halos.raw 0.1 1 8H 2 1 1 0
./voz1b1 eight_halos.raw 0.1 1 8H 2 1 1 1
./voztie 2 8H
